language: python
sudo: false # Use container-based infrastructure

env:
  global:
    - LUAROCKS=2.4.4
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit" # latest stable version (2.0.4)
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

branches:
  only:
    - property_testing

before_install:
  - pip install hererocks
  - hererocks lua_install --$LUA -rlatest
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacov
  - luarocks install luacheck
  - luarocks install luacov-coveralls

script:
  - make test

after_success:
  -make coverage
