language: c
sudo: false

env:
  global:
    - LUAROCKS=2.4.4
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - property_testing

before_install:
  - luarocks install luacov
  - luarocks install luacheck
  - luarocks install luacov-coveralls

script:
  - make test

after_success:
  -make coverage
