language: python
sudo: false # Use container-based infrastructure

env:
  global:
    - TEST_PACKAGE_PATH='package.path = "./test/?.lua;./test/util/?.lua;" .. package.path'
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0" # latest stable in 2.0 series
    - LUA="luajit 2.1" # latest beta in 2.1 series

branches:
  only:
    - build_pipeline
    - remove_makefile

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks install luacov
  - luarocks install luacheck
  - luarocks install luacov-coveralls

script:
  - lua -e "$TEST_PACKAGE_PATH" -lluacov test/test.lua

after_success:
  - luacov-coveralls
